name: Count Lines of Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install tokei
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        cargo install tokei

    - name: Run tokei
      run: |
        tokei -o json > tokei_output.json
        cat tokei_output.json
